# Generates csrc/sm90_gemm_coop_ctapp.hpp: the stock CUTLASS SM90 cooperative kernel (third_party/cutlass/include/cutlass/gemm/
# kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp) renamed to GemmUniversalCtapp with the Phase-4 hooks (csrc/ctapp_tp4.cuh)
# spliced in. Re-run after a CUTLASS update. Each patch must match exactly once.
import re, os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = f"{ROOT}/third_party/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp"
DST = f"{ROOT}/csrc/sm90_gemm_coop_ctapp.hpp"
s = open(SRC).read()

def once(old, new, flags=0):
    global s
    n = len(re.findall(old, s, flags)) if flags else s.count(old)
    assert n == 1, (n, old[:60])
    s = re.sub(old, new, s, flags=flags) if flags else s.replace(old, new)

# 1. own class instead of the GemmUniversal partial specialisation
once(r"class GemmUniversal<\n.*?>>>\n\{", "class GemmUniversalCtapp\n{", re.S)
once("#pragma once\n", "#pragma once\n// GENERATED by scripts/gen_coop_ctapp.py from CUTLASS sm90_gemm_tma_warpspecialized_cooperative.hpp -- do not edit.\n#include \"ctapp_tp4.cuh\"\n")
# 2. params
once("    TileSchedulerArguments scheduler{};\n  };", "    TileSchedulerArguments scheduler{};\n    CtappTp4Params ctapp{};\n  };")
once("    TileSchedulerParams scheduler{};\n    void* workspace{nullptr};", "    TileSchedulerParams scheduler{};\n    CtappTp4Params ctapp{};\n    void* workspace{nullptr};")
once("      scheduler,\n      workspace\n    };", "      scheduler,\n      args.ctapp,\n      workspace\n    };")
# 3. consumer-side wait before the mainloop loads (TMA producer warp)
once("          collective_mainloop.load(\n            params.mainloop,", "          tp4_wait_panel(params.ctapp, work_tile_info.M_idx);\n          collective_mainloop.load(\n            params.mainloop,")
# 4. producer-side signal + deferred slice reduction (consumer warp groups)
once("      bool do_store_tail = false;\n", "      bool do_store_tail = false;\n      int tp4_prev_m = -1, tp4_prev_n = -1;\n")
once("NumMmaWarpGroups, consumer_warp_group_idx);\n\n        if (TileScheduler::compute_epilogue(", "NumMmaWarpGroups, consumer_warp_group_idx);\n\n        tp4_before_epilogue(params.ctapp, work_tile_info.M_idx);\n        if (TileScheduler::compute_epilogue(")
once("          do_store_tail = true;\n        }\n", "          do_store_tail = true;\n        }\n        tp4_after_store(params.ctapp, work_tile_info.M_idx, work_tile_info.N_idx, tp4_prev_m, tp4_prev_n, mma_thread_idx);\n")
once("          epi_store_pipe_producer_state\n        );\n      }\n    } // Consumer Warp Groups End", "          epi_store_pipe_producer_state\n        );\n      }\n      tp4_finish(params.ctapp, tp4_prev_m, tp4_prev_n, mma_thread_idx);\n    } // Consumer Warp Groups End")
# 5. the two idle producer warps become the reducer (mode 1)
once("      else if (producer_warp_role == ProducerWarpRole::MainloopAux) {\n        if constexpr (IsMainloopAuxiliaryLoadNeeded) {",
     "      else if (params.ctapp.mode == 1 && !IsMainloopAuxiliaryLoadNeeded && !is_epi_load_needed &&\n"
     "               (producer_warp_role == ProducerWarpRole::Epilogue || producer_warp_role == ProducerWarpRole::MainloopAux)) {\n"
     "        tp4_reducer(params.ctapp, scheduler, work_tile_info, producer_warp_role == ProducerWarpRole::MainloopAux ? 1 : 0, lane_idx);\n"
     "      }\n"
     "      else if (producer_warp_role == ProducerWarpRole::MainloopAux) {\n        if constexpr (IsMainloopAuxiliaryLoadNeeded) {")
# 6. register split is left at the stock 40 (producer) / 232 (consumer): 64/224 sums to exactly 65536 but setmaxnreg.inc
#    then never completes (kernel hangs even in mode 0). The reducer path (tp4::reduce_slice64) must therefore stay <= 40
#    registers; the standalone mm_reduce_probe_kernel in gemm_tp4.cu reports its footprint (31 with kRedBatch = 2).
# 7. PDL: mode 2 syncs on its own panel counters, so it must not wait for the primary grid to finish
_old = "cutlass::arch::wait_on_dependent_grids();"
assert s.count(_old) == 3, s.count(_old)
s = s.replace(_old, "if (params.ctapp.mode != 2) cutlass::arch::wait_on_dependent_grids();")
open(DST, "w").write(s)
print("wrote", DST, len(s.splitlines()), "lines")
